apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cypress-pipeline-run
#  annotations:
#    argocd.argoproj.io/hook: PostSync
spec:
  resources:
    - name: my-repo
      resourceRef:
        name: github-resource
  pipelineRef:
    name: cypress-pipeline
